### ISSUE TITLE
Plotting arithmetic expressions doesn't work when subject is all

### ISSUE THREAD

**Issue by markusrobertjonsson** [learningsimulator/learningsimulator#201]
Plotting arithmetic expressions doesn't work when subject is all, for example in this script:

```
        n_subjects        = 3
        mechanism         = a
        behaviors         = response, no_response
        stimulus_elements = background, stimulus, reward
        start_v           = -1
        alpha_v           = 0.1
        alpha_w           = 1
        u                 = reward:10, default:0

        @PHASE training stop: stimulus==7
        START       stimulus   | response: REWARD | NO_REWARD
        REWARD      reward     | @omit_learn, START
        NO_REWARD   background | @omit_learn, START

        @run training

        xscale: stimulus
        
        subject: all
        @plot v(stimulus->response) + 1
```

The error below occurs:
```
Traceback (most recent call last):
  File "C:\Users\markj\sb\learningsimulator\gui.py", line 287, in simulate
    self.script_obj.postproc(self.simulation_data, self.progress)
  File "C:\Users\markj\sb\learningsimulator\parsing.py", line 82, in postproc
    self.script_parser.postcmds.run(simulation_data, progress)
  File "C:\Users\markj\sb\learningsimulator\parsing.py", line 926, in run
    cmd.run(simulation_data)
  File "C:\Users\markj\sb\learningsimulator\parsing.py", line 994, in run
    raise EvalException(f"Expression evaluation failed.", self.lineno)
exceptions.EvalException: Error on line 20: Expression evaluation failed.
```

With `subject=average` the error does not occur.

**Comment by markusrobertjonsson** [comment]
Fix included in https://github.com/learningsimulator/learningsimulator/pull/202.
